name: Set Deployment Environment
author: ServiceRocket-Garden
description: Set corresponding deployment environment base on branch name

runs:
  using: "composite"
  steps:
    - name: Set env to staging
      if: endsWith(github.ref, '/develop')
      run: |
        echo "ENVIRONMENT=staging" >> $GITHUB_ENV
      shell: bash
    - name: Set env to production
      if: endsWith(github.ref, '/master')
      run: |
        echo "ENVIRONMENT=production" >> $GITHUB_ENV
      shell: bash