name: Deployment
run-name: Deploy[${{ github.ref_name }}]-${{github.event.head_commit.message}}
on:
  push:
    branches: ['develop', 'main']

concurrency: cd-${{ github.ref_name }}

jobs:
  get-env:
    runs-on: ubuntu-latest
    outputs:
      output: ${{ steps.concat.outputs.data }}
    steps:
      - id: step1
        if: ${{github.ref_name == 'develop'}}
        run: echo "data=staging" >> "$GITHUB_OUTPUT"
      - id: step2
        if: ${{github.ref_name == 'main'}}
        run: echo "data=production" >> "$GITHUB_OUTPUT"
      - id: concat
        run: echo "data=${{ steps.step1.outputs.data }}${{ steps.step2.outputs.data }}" >> "$GITHUB_OUTPUT"

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: get-env
    environment: ${{needs.get-env.outputs.output}}
    env:
      FORGE_EMAIL: ${{ vars.FORGE_EMAIL }}
      FORGE_API_TOKEN: ${{ secrets.FORGE_API_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js and install dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: check consolidation 2
        run: echo "The value of OUTPUT is $OUTPUT"
        env:
          OUTPUT: ${{needs.get-env.outputs.output}}

      - name: check consolidation 1
        run: echo "The value of FORGE_EMAIL is $FORGE_EMAIL"

      - name: print name
        run: echo "The value of run name is ${{github.ref_name}} ${{github.event.head_commit.message}} "
