name: Retrieve Forge logs

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Forge App environment
        required: true
        options:
          - staging
          - production
      since:
        description: view logs since the specified time. valid formats:YYYY-MM-DD, ISO 8061 timestamp or a relative time (e.g 5m, 10h, 2d)
        required: false
        default: 30d
      limit:
        description: number of invocations to return
        required: false
        type: number
        default: 1000
      grouped:
        description: group logs by invocation ID
        required: false
        type: boolean
        default: true
      verbose:
        description: enable verbose mode
        required: false
        type: boolean
        default: true
      invocation:
        description: view logs for a given invocation ID
        required: false
      
jobs:
  retrieve:
    name: Retrieve Forge App Logs
    runs-on: ubuntu-latest
    steps:
      - name: Print job's parameter values
        run: echo "${{ toJSON(env) }}"

      # Retrieve Forge logs
      - name: Retrieve logs
        run:  echo "${{ env.grouped}} Expression result ${{ env.grouped == 'true' && ' --grouped' || '' }}"
        
      # Retrieve Forge logs
      - name: Retrieve logs2
        run:  echo " ${{ env.verbose}} Expression result ${{ env.verbose == 'true' && ' --verbose' || '' }}"

