name: Retrieve Forge logs

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: environment
      since:
        description: view logs since the specified time
        required: false
        default: 30d
      grouped:
        description: group logs by invocation ID
        required: false
        type: boolean
        default: true
      verbose:
        description: enable verbose mode
        required: false
        type: boolean
        default: true
      limit:
        description: number of invocations to return
        required: false
        default: '1000'
      invocation:
        description: view logs for a given invocation ID
        required: false
      
jobs:
  retrieve:
    name: Retrieve Forge App Logs
    runs-on: ubuntu-latest
    steps:
      - name: Print job's parameter values
        run: echo "${{ toJSON(env) }}"

      # Retrieve Forge logs
      - name: Retrieve logs
        run:  echo "${{ env.grouped}} Expression result ${{ env.grouped == 'true' && ' --grouped' || '' }}"
        
      # Retrieve Forge logs
      - name: Retrieve logs2
        run:  echo " ${{ env.verbose}} Expression result ${{ env.verbose == 'true' && ' --verbose' || '' }}"

