name: Retrieve Forge logs

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: environment
      since:
        description: view logs since the specified time
        default: 30d
      grouped:
        description: group logs by invocation ID
        type: boolean
        default: true
      verbose:
        description: enable verbose mode
        type: boolean
        default: true
      limit:
        description: number of invocations to return
        default: '1000'
      invocation:
        description: view logs for a given invocation ID
      
jobs:
  retrieve:
    name: Retrieve Forge App Logs
    runs-on: ubuntu-latest
    environment: ${{github.event.inputs.environment}}
    env:
      FORGE_EMAIL: ${{ vars.FORGE_EMAIL }}
      FORGE_API_TOKEN: ${{ secrets.FORGE_API_TOKEN }}

    steps:
      - name: Print job's parameter values
        run: echo "${{ toJSON(env) }}"

      # Retrieve Forge logs
      - name: Retrieve logs
        run:  echo "${{ env.grouped}} Expression result ${{ env.grouped == 'true' && ' --grouped' || '' }}"
        
      # Retrieve Forge logs
      - name: Retrieve logs2
        run:  echo " ${{ env.verbose}} Expression result ${{ env.verbose == 'true' && ' --verbose' || '' }}"

      - name: check consolidation 1
        run: echo "The value of FORGE_EMAIL is $FORGE_EMAIL"

